# Generated by Django 5.2.13 on 2026-04-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandingFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LandingFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(default="sparkles", max_length=40)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Analytics that look premium, move fast, and stay easy to manage.",
                        max_length=220,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Launch a sharp, trust-building landing page for your analytics brand and control every piece of copy from the Django admin."
                    ),
                ),
                (
                    "primary_cta_label",
                    models.CharField(default="Book a Demo", max_length=60),
                ),
                (
                    "primary_cta_url",
                    models.CharField(default="#contact", max_length=255),
                ),
                (
                    "secondary_cta_label",
                    models.CharField(default="View Features", max_length=60),
                ),
                (
                    "secondary_cta_url",
                    models.CharField(default="#features", max_length=255),
                ),
                (
                    "hero_panel_title",
                    models.CharField(default="Inside the platform", max_length=120),
                ),
                (
                    "hero_panel_body",
                    models.TextField(
                        default="Upload data, explore structured insights, surface trends, and deliver reports from one polished workflow."
                    ),
                ),
                (
                    "features_title",
                    models.CharField(
                        default="Everything teams need to move from raw files to usable insight",
                        max_length=120,
                    ),
                ),
                (
                    "features_body",
                    models.TextField(
                        default="The layout stays consistent, while the content comes fully from your SQLite database through Django models."
                    ),
                ),
                (
                    "process_title",
                    models.CharField(default="How AnalyticABD works", max_length=120),
                ),
                (
                    "testimonial_title",
                    models.CharField(default="What early teams say", max_length=120),
                ),
                (
                    "faq_title",
                    models.CharField(
                        default="Questions people usually ask first", max_length=120
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(
                        default="Ready to launch the same premium feel with database-managed content?",
                        max_length=180,
                    ),
                ),
                (
                    "cta_body",
                    models.TextField(
                        default="Use the Django admin to update text, stats, features, testimonials, and FAQs without touching templates."
                    ),
                ),
                ("cta_label", models.CharField(default="Start Now", max_length=60)),
                ("cta_url", models.CharField(default="/admin/", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Landing Page",
                "verbose_name_plural": "Landing Page",
            },
        ),
        migrations.CreateModel(
            name="LandingStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("value", models.CharField(max_length=40)),
                ("description", models.CharField(blank=True, max_length=140)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LandingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LandingTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("author_name", models.CharField(max_length=120)),
                ("author_role", models.CharField(blank=True, max_length=120)),
                ("company", models.CharField(blank=True, max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="AnalyticABD", max_length=120)),
                (
                    "nav_label",
                    models.CharField(
                        default="Advanced analytics platform", max_length=120
                    ),
                ),
                (
                    "hero_badge",
                    models.CharField(
                        default="Built for data-heavy teams", max_length=120
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        default="AnalyticABD helps teams turn raw data into clear decisions.",
                        max_length=255,
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Branding",
                "verbose_name_plural": "Site Branding",
            },
        ),
    ]
