# Generated by Django 5.2.13 on 2026-04-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyticabd", "0003_parent_brand_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="cta_body",
            field=models.TextField(
                default="Use the Django admin to manage company messaging, featured products, logos, tags, testimonials, and FAQs without editing templates."
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="cta_label",
            field=models.CharField(default="Open Admin", max_length=60),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="cta_title",
            field=models.CharField(
                default="Want to showcase your products from one polished parent-brand site?",
                max_length=180,
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="faq_title",
            field=models.CharField(
                default="Common questions about the company and its products",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="features_body",
            field=models.TextField(
                default="The landing page introduces the company, explains the product strategy, and gives each product its own clear place to stand out."
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="features_title",
            field=models.CharField(
                default="How the parent brand communicates trust", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="hero_panel_body",
            field=models.TextField(
                default="A parent brand that can present multiple products clearly, route visitors to each product site, and manage all landing content from Django admin."
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="hero_panel_title",
            field=models.CharField(default="What ABD Site represents", max_length=120),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="hero_subtitle",
            field=models.TextField(
                default="ABD Site is the parent company behind practical software products. From analytics platforms like Saiha to future vertical tools, we design, ship, and manage products that solve real business problems."
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="hero_title",
            field=models.CharField(
                default="We build products that turn difficult workflows into simple, usable digital experiences.",
                max_length=220,
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="primary_cta_label",
            field=models.CharField(default="Explore Products", max_length=60),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="primary_cta_url",
            field=models.CharField(default="#products", max_length=255),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="process_title",
            field=models.CharField(
                default="How ABD Site presents products", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="secondary_cta_label",
            field=models.CharField(default="Contact Us", max_length=60),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="secondary_cta_url",
            field=models.CharField(default="#contact", max_length=255),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="testimonial_title",
            field=models.CharField(
                default="How teams describe the experience", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="sitebranding",
            name="footer_text",
            field=models.CharField(
                default="ABD Site builds and launches focused digital products, including analytics-first platforms like Saiha.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sitebranding",
            name="hero_badge",
            field=models.CharField(
                default="Products built for serious operational work", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="sitebranding",
            name="nav_label",
            field=models.CharField(
                default="Parent company for digital products", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="sitebranding",
            name="site_name",
            field=models.CharField(default="ABD Site", max_length=120),
        ),
    ]
