# Generated by Django 5.2.13 on 2026-04-19 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyticabd", "0004_alter_landingpage_cta_body_and_more"),
        ("analyticabd", "0004_upgrade_marketing_content"),
    ]

    operations = []
