# Generated by Django 5.2.13 on 2026-07-15 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyticabd", "0006_contactlead_public_cta"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentApiClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=120)),
                (
                    "shared_secret",
                    models.CharField(
                        help_text="Shared HMAC secret used by the client and the payment service.",
                        max_length=255,
                    ),
                ),
                (
                    "allowed_return_origin",
                    models.CharField(
                        blank=True,
                        help_text="Example: https://quantly.analyticabd.xyz",
                        max_length=255,
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional signed webhook destination for payment result updates.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["client_id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, unique=True
                    ),
                ),
                ("internal_order_id", models.CharField(max_length=100)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("subscription", "Subscription"), ("topup", "Top Up")],
                        max_length=20,
                    ),
                ),
                ("product_code", models.CharField(max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="BDT", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("initialized", "Initialized"),
                            ("pending_verification", "Pending Verification"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("verification_failed", "Verification Failed"),
                        ],
                        default="created",
                        max_length=32,
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=200)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("customer_phone", models.CharField(blank=True, max_length=50)),
                ("success_return_url", models.URLField(blank=True)),
                ("fail_return_url", models.URLField(blank=True)),
                ("cancel_return_url", models.URLField(blank=True)),
                (
                    "merchant_transaction_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, unique=True
                    ),
                ),
                (
                    "eps_transaction_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("redirect_url", models.URLField(blank=True, max_length=500)),
                ("financial_entity", models.CharField(blank=True, max_length=120)),
                ("eps_status", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("raw_initialize_response", models.JSONField(blank=True, default=dict)),
                ("raw_verify_response", models.JSONField(blank=True, default=dict)),
                ("last_error", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_intents",
                        to="analyticabd.paymentapiclient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("client", "internal_order_id")},
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=80)),
                ("source", models.CharField(blank=True, max_length=40)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="analyticabd.paymentintent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApiRequestNonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nonce", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nonces",
                        to="analyticabd.paymentapiclient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("client", "nonce")},
            },
        ),
    ]
