# Generated by Django 5.2.13 on 2026-07-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyticabd", "0007_paymentapiclient_paymentintent_paymentevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentintent",
            name="callback_eps_transaction_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="callback_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="callback_status",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
